feat: Making use of standard of opentracing tags
ory/instrumentedsql pull request #1
Opened 2021-08-09 14:41 UTC by dadrus

This is a PR for the changes described in https://github.com/luna-duclos/instrumentedsql/issues/43 and actually requested in https://github.com/luna-duclos/instrumentedsql/pull/44 (unfortunately still without an answer).

Please consider it a WIP for now. If you see any issues with the current approach, please let me know. Further updates will come soon.

2021-08-10 07:02 UTC, aeneasr requested changes

2021-08-10 07:02 UTC, aeneasr commented on driver.go
> +		d.ComponentName = "luna-duclos" // alternatively the old "database/sql"
For BC I would keep this as `database/sql` as it is also clear what we're tracing :)

2021-08-10 07:21 UTC, dadrus commented on driver.go
> +		d.ComponentName = "luna-duclos" // alternatively the old "database/sql"
Yes. This was one of the todos :)

2021-08-10 08:22 UTC, dadrus commented on opts.go
> +func (o *opts) setDefaultLabels(span Span) {
In principle, I would say, I'm done. But, if you take a look on how the project is organized, you'll see it abstracts different tracing implementations. The implementation I've done so far breaks this abstraction by introducing this function on the opts struct.
Actually this implementation must IMHO be moved to opentracing/tracer.go (https://github.com/ory/instrumentedsql/blob/afb87fb308ed63d7fcb35ef85cf46ba6eb13e815/opentracing/tracer.go#L1) implementation. To make use of the tags without breaking the abstraction, the NewTracer function (https://github.com/ory/instrumentedsql/blob/afb87fb308ed63d7fcb35ef85cf46ba6eb13e815/opentracing/tracer.go#L24) would require the options defined during the initialization of the wrapper driver.

What do you think?

2021-08-10 09:55 UTC, aeneasr commented on opts.go
> +func (o *opts) setDefaultLabels(span Span) {
That sounds like a possibility! Unfortunately I am not well enough informed about the code used here. Keep in mind that the original author was in the Go core team (afaik) so there might be a reason for choosing to implement it this way. Primarily I think that the submodules are published because we don't want to import AWS SDK unless we also use XRay.

As you can see from the git history, this was introduced at a later stage: https://github.com/ory/instrumentedsql/commit/ae9b978a0fdda36e17e03d176f4c56978888d75b#diff-6366931f4ad9b9b1d5cd68e88b8408670cdae97858f35f967bbc1b7424955de2

However, I am all for supporting the new labels across the different tracers!

2021-08-16 12:42 UTC, dadrus commented
@aeneasr: In principle, I'm done. 
The only thing, which is open is how you would like to deal with the go.mod files of the sub-modules. All of them have
```
replace (
	github.com/luna-duclos/instrumentedsql => ../
)
```
right now to let the module use the proper version.

2021-08-16 12:42 UTC, dadrus commented
When this PR is merged, I'll open new PRs for kratos and hydra to make use of this implementation.

2021-08-30 12:28 UTC, aeneasr reviewed
It's a bit difficult for me to review this - I would propose that you set up a demo using e.g. kratos using this branch and show that SQL statements are properly being traced. Then I feel comfortable to merge this :)

2021-09-03 11:42 UTC, merged